CREATE TABLE `put_options` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ticker` VARCHAR(10) NOT NULL,
  `contract_symbol` VARCHAR(50) NOT NULL,
  `expiration_date` DATE NOT NULL,
  `strike_price` DECIMAL(10,2) NOT NULL,
  `last_price` DECIMAL(10,4) NULL,
  `bid` DECIMAL(10,4) NULL,
  `ask` DECIMAL(10,4) NULL,
  `change` DECIMAL(10,4) NULL,
  `percent_change` DECIMAL(10,4) NULL,
  `volume` INT NULL,
  `open_interest` INT NULL,
  `implied_volatility` DECIMAL(10,6) NULL,
  `in_the_money` BOOLEAN NULL,
  `contract_size` VARCHAR(20) NULL,
  `currency` VARCHAR(3) NULL,
  `last_trade_date` DATETIME NULL,
  `created_at` DATE NOT NULL DEFAULT (CURDATE()),
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_contract_symbol_date` (`contract_symbol`, `created_at`),
  KEY `idx_ticker_expiration` (`ticker`, `expiration_date`),
  KEY `idx_strike_price` (`strike_price`),
  KEY `idx_expiration_date` (`expiration_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci; 